### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Abduoit** [vanadiumlabs/pypose#16]
Hi

I git clone pypose, and I run ./Pypose.py in order to control Phantomx Pincher arm, but I can NOT detect my five servos. I get the following errors. 

Any help please  ????

```
grasp001@grasp001:~/pypose$ ./PyPose.py 
PyPose starting... 
Opening port: /dev/ttyUSB0
Traceback (most recent call last):
  File "tools/ArbotixTerminal.py", line 66, in OnEnterChar
    keycode = event.GetKeyCode()
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "tools/ArbotixTerminal.py", line 66, in OnEnterChar
    keycode = event.GetKeyCode()
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "tools/ArbotixTerminal.py", line 66, in OnEnterChar
    keycode = event.GetKeyCode()
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "tools/ArbotixTerminal.py", line 66, in OnEnterChar
    keycode = event.GetKeyCode()
RuntimeError: maximum recursion depth exceeded
```

**Comment by mikeferguson** [comment]
Archiving shortly
