### ISSUE TITLE
Python gets confused about Terminal module import

### ISSUE THREAD

**Issue by hokster7** [vanadiumlabs/pypose#5]
I'm running with Python installed from Homebrew and found this error.

```
PyPose starting... 
./PyPose.py:410: wxPyDeprecationWarning: Using deprecated class PySimpleApp. 
  app = wx.PySimpleApp()
Traceback (most recent call last):
  File "./PyPose.py", line 411, in <module>
    frame = editor()
  File "./PyPose.py", line 96, in __init__
    name = getattr(module, "NAME")
AttributeError: 'module' object has no attribute 'NAME'
```

Digging deeper, I found that Python was importing the wrong module. Mac environments actually have a `Terminal` module defined in the following typical location.

```
$ python
>>> import Terminal
>>> Terminal.__file__
'/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages/Terminal/__init__.pyc'
>>> 
```

I propose renaming `Terminal` to something else to avoid the name collision.

**Comment by hokster7** [comment]
Related issue: https://code.google.com/p/arbotix/issues/detail?id=35

**Comment by hokster7** [comment]
Sorry, this issue has been resolved actually!
