### ISSUE TITLE
PyPose doesn't run with 64-bit Python on Mac (wxPython 2.8)

### ISSUE THREAD

**Issue by hokster7** [vanadiumlabs/pypose#7]
I installed `wxPython2.8-osx-unicode-universal-py2.7.pkg` (taken from the [download site](http://wxpython.org/download.php): see the section **Mac OS X Binaries**).

Executing `./Pose.py` blows up with the following stack trace:

```
Traceback (most recent call last):
  File "./PyPose.py", line 24, in <module>
    import wx
  File "/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: dlopen(/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core_.so, 2): no suitable image found.  Did find:
    /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core_.so: no matching architecture in universal wrapper
```

**Comment by hokster7** [comment]
I found that the solution for this is to force your 64-bit Python installation to run in 32-bit mode by doing:

```
python-32 PyPose.py
```

PyPose is a bit happier and runs okay this way.
